[package]
name = "easy-ffi-wrapper"
version = "0.1.1"
description = "Types and utilities to enable writing C FFI wrappers easily."
authors = ["HERE Europe B.V."]
license = "Apache-2.0"
edition = "2018"
repository = "https://github.com/heremaps/easy-ffi"