name: easy-ffi-rs
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  CARGO_TERM_COLORS: always

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          cd lib-rs
          cargo build --workspace
          cargo build --workspace --all-features
      - name: Run tests
        run: |
          cd lib-rs
          cargo test --workspace
          cargo test --workspace --all-features